### ISSUE TITLE
error: cannot access zzbgl class file for com.google.android.gms.internal.zzbgl not found

### ISSUE THREAD

**Issue by ghost** [hypertrack/uber_for_x_android#3]
error: cannot access zzbgl class file for com.google.android.gms.internal.zzbgl not found on getting phone number from firebase.

**Comment by anshudwibhashi** [comment]
This happens when different dependencies in your gradle file use different, conflicting versions of Firebase and Google Play Services. The way Firebase and Hypertrack have their dependencies makes this especially tricky to fix.

I just fixed this, and made a pull-request. As soon as Hypertrack accepts it, the bugs will be fixed!

**Comment by tulushev** [comment]
The project is rewritten, feel free to reopen the issue if it persists.
