### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by Azazel17** [hypertrack/uber_for_x_android#5]
I have this 5 issues 

What is wrong? 

D:/hypertrack/uber_for_x_android/consumer |  
-- | --
app/src/main/java |  
com/hypertrack/uber_consumer/base/MyHyperTrackMapAdapter.java |  
error: method does not override or implement a method from a supertype |  
com/hypertrack/uber_consumer/activities/GenerateRideActivity.java |  
error: cannot find symbol method showBackArrow(boolean) |  
error: cannot find symbol method setShowCurrentLocation(boolean) |  
error: cannot find symbol method setShowCurrentLocation(boolean) |  
com/hypertrack/uber_consumer/activities/GetHyperTrackUserActivity.java |

**Comment by KaipraDevs** [comment]
I also have all these errors..Please Hypertrack get a way to solve them..Hope you will..
Thank You

**Comment by anshudwibhashi** [comment]
I had these bugs too.

All these errors are fixed by upgrading to Hypertrack 0.7.39 and resolving dependency-version-conflicts. The way Firebase and Hypertrack have their dependencies makes this especially tricky to fix.

I just fixed this, and made a pull-request. As soon as Hypertrack accepts it, the bugs will be fixed!

**Comment by tulushev** [comment]
The project is rewritten, feel free to reopen the issue if it persists.
